from django.db import models

class Aprovisionamiento(models.Model):
    Usuario = models.CharField(max_length=255, null=True, blank=True)
    Cedula = models.IntegerField(null=True, blank=True)
    Nombre = models.CharField(max_length=255, null=True, blank=True)
    Celula = models.CharField(max_length=100, null=True, blank=True)
    Lider = models.CharField(max_length=255, null=True, blank=True)




class Backlog(models.Model):
    IdAprovisionamiento = models.TextField(max_length=255, null=True, blank=True) 
    ViabilidadOrigen = models.TextField(max_length=255, null=True, blank=True)
    AsesorComercial = models.TextField(max_length=255, null=True, blank=True,)
    TipoOperacionPlan = models.CharField(max_length=255, null=True, blank=True,default=None )
    CategoríaSM = models.CharField(max_length=255, null=True, blank=True, default=None)
    Estado = models.CharField(max_length=255, null=True, blank=True, default=None)
    IdServicio = models.CharField(max_length=255, null=True, blank=True, default=None)
    GrupoAsignado = models.CharField(max_length=255, null=True, blank=True, default=None)
    Mes = models.CharField(max_length=255, null=True, blank=True, default=None)
    FechaCreación = models.CharField(max_length=255, null=True, blank=True, default=None)
    ANS = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoOperacion = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoCliente = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoComercial = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoETB = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoTercero = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoTotal = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoReal = models.CharField(max_length=255, null=True, blank=True, default=None)
    CumpleNoCumple = models.CharField(max_length=255, null=True, blank=True, default=None)
    FaseActual = models.CharField(max_length=255, null=True, blank=True, default=None)
    NombreProducto = models.CharField(max_length=255, null=True, blank=True, default=None)
    TipoSolicitud = models.CharField(max_length=255, null=True, blank=True, default=None)
    CausalRetiro = models.CharField(max_length=255, null=True, blank=True, default=None)
    AnchoBanda = models.CharField(max_length=255, null=True, blank=True, default=None)
    MedioUltimaMilla = models.CharField(max_length=255, null=True, blank=True, default=None)
    CuentaCliente = models.CharField(max_length=255, null=True, blank=True, default=None)
    NIT = models.CharField(max_length=255, null=True, blank=True, default=None)
    ProveedorUltimaMilla = models.CharField(max_length=255, null=True, blank=True, default=None)
    Asignadoa = models.CharField(max_length=255, null=True, blank=True, default=None)
    Modificadopor = models.CharField(max_length=255, null=True, blank=True, default=None)
    DireccionPrincipal = models.CharField(max_length=255, null=True, blank=True, default=None)
    SucursalInstalcion = models.CharField(max_length=255, null=True, blank=True, default=None)
    CiudadInstalacion = models.CharField(max_length=255, null=True, blank=True, default=None)
    FechaActulización = models.CharField(max_length=255, null=True, blank=True, default=None)
    UltimaAnotación = models.CharField(max_length=255, null=True, blank=True, default=None)
    SegmentoResumen = models.CharField(max_length=255, null=True, blank=True, default=None)
    UltimaTarea = models.CharField(max_length=255, null=True, blank=True, default=None)
    AltasTramites = models.CharField(max_length=255, null=True, blank=True, default=None)
    ValorRecurrente = models.CharField(max_length=255, null=True, blank=True, default=None)
    DELTA = models.CharField(max_length=255, null=True, blank=True, default=None)
    ONETIME = models.CharField(max_length=255, null=True, blank=True, default=None)
    DELTAEQUIPOS = models.CharField(max_length=255, null=True, blank=True, default=None)
    DELTAEQUIPOSLB = models.CharField(max_length=255, null=True, blank=True, default=None)
    ProyeccionMesLB = models.CharField(max_length=255, null=True, blank=True, default=None)
    FechaEntregaLB = models.CharField(max_length=255, null=True, blank=True, default=None)
    EstadoLB = models.CharField(max_length=255, null=True, blank=True, default=None)
    CODIGO_TIPO = models.CharField(max_length=255, null=True, blank=True, default=None)
    SUB_CODIGO_TIPO = models.CharField(max_length=255, null=True, blank=True, default=None)
    GESTIONOGESTIO = models.CharField(max_length=255, null=True, blank=True, default=None)
    ESTADO_GENERAL = models.CharField(max_length=255, null=True, blank=True, default=None)
    RESPONSABLE = models.CharField(max_length=255, null=True, blank=True, default=None)
    ACCIONATOMAR = models.CharField(max_length=255, null=True, blank=True, default=None)
    FechaPactadaCliente = models.CharField(max_length=255, null=True, blank=True, default=None)
    FECHASEGUIMIENTOSTANDBY = models.TextField(null=True, blank=True, default=None)
    ResponsableStandby = models.CharField(max_length=255, null=True, blank=True, default=None)
    FechaEntregaCliente2 = models.TextField( null=True, blank=True, default=None)
    FechaFacturación = models.DateTimeField(null=True, blank=True, default=None)
    FechaFinalización = models.TextField(null=True, blank=True, default=None)
    SemanaProyección = models.CharField(max_length=255, null=True, blank=True, default=None)
    MasoMenos = models.CharField(max_length=255, null=True, blank=True, default=None)
    SemanaFact = models.CharField(max_length=255, null=True, blank=True, default=None)
    Backlog = models.CharField(max_length=255, null=True, blank=True, default=None)
    PrimerDíaMes = models.TextField(null=True, blank=True, default=None)
    UltimoDíaMes = models.TextField(null=True, blank=True, default=None)
    DíasFactura = models.CharField(max_length=255, null=True, blank=True, default=None)
    ValorProrrateadoOperación = models.CharField(max_length=255, null=True, blank=True, default=None)
    TFacturacion = models.CharField(max_length=255, null=True, blank=True, default=None)
    DíasFacturaIngresos = models.CharField(max_length=255, null=True, blank=True, default=None)
    ValorProrrateadoIngresoMarzo = models.CharField(max_length=255, null=True, blank=True, default=None)
    ValorProrrateadoIngresoAbril = models.CharField(max_length=255, null=True, blank=True, default=None)
    TiempoMedioBolsa = models.CharField(max_length=255, null=True, blank=True, default=None)
    ClasificaciónTipoCliente = models.CharField(max_length=255, null=True, blank=True, default=None)



class AbiertasRetiros(models.Model):
    IdAprovisionamiento = models.CharField(max_length=255, null=True, blank=True)
    ViabilidadOrigen = models.CharField(max_length=255, null=True, blank=True)
    AsesorComercial = models.CharField(max_length=255, null=True, blank=True)
    TipoOperacionPlan = models.CharField(max_length=255, null=True, blank=True)
    CategoríaSM = models.CharField(max_length=255, null=True, blank=True)
    Estado = models.CharField(max_length=255, null=True, blank=True)
    IdServicio = models.CharField(max_length=255, null=True, blank=True)
    GrupoAsignado = models.CharField(max_length=255, null=True, blank=True)
    Mes = models.CharField(max_length=255, null=True, blank=True)
    FechaCreación = models.CharField(max_length=255, null=True, blank=True)
    FechaEsperada06 = models.CharField(max_length=255, null=True, blank=True)
    FechaInicioFacturacion = models.CharField(max_length=255, null=True, blank=True)
    ANS = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoOperacion = models.CharField(max_length=255, null=True, blank=True)
    TiempoCliente = models.CharField(max_length=255, null=True, blank=True)
    TiempoComercial = models.CharField(max_length=255, null=True, blank=True)
    TiempoETB = models.CharField(max_length=255, null=True, blank=True)
    TiempoTercero = models.CharField(max_length=255, null=True, blank=True)
    TTAbierto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    CumpleNoCumple = models.CharField(max_length=255, null=True, blank=True)
    FaseActual = models.CharField(max_length=255, null=True, blank=True)
    NombreProducto = models.CharField(max_length=255, null=True, blank=True)
    TipoSolicitud = models.CharField(max_length=255, null=True, blank=True)
    CausalRetiro = models.CharField(max_length=255, null=True, blank=True)
    AnchoBanda = models.CharField(max_length=255, null=True, blank=True)
    MedioUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    CuentaCliente = models.CharField(max_length=255, null=True, blank=True)
    NIT = models.DecimalField(max_digits=15, decimal_places=0, null=True, blank=True)
    ProveedorUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    Asignadoa = models.CharField(max_length=255, null=True, blank=True)
    Modificadopor = models.CharField(max_length=255, null=True, blank=True)
    DireccionPrincipal = models.CharField(max_length=255, null=True, blank=True)
    SucursalInstalcion = models.CharField(max_length=255, null=True, blank=True)
    CiudadInstalacion = models.CharField(max_length=255, null=True, blank=True)
    UltimaFechaAnotación = models.CharField(max_length=255, null=True, blank=True)
    UltimaAnotaciónResumen = models.CharField(max_length=255, null=True, blank=True)
    TipoSuspensión = models.CharField(max_length=255, null=True, blank=True)
    Segmento = models.CharField(max_length=255, null=True, blank=True)



class Abiertas(models.Model):
    IdAprovisionamiento = models.CharField(max_length=255, null=True, blank=True)
    ViabilidadOrigen = models.CharField(max_length=255, null=True, blank=True)
    AsesorComercial = models.CharField(max_length=255, null=True, blank=True)
    TipoOperacionPlan = models.CharField(max_length=255, null=True, blank=True)
    CategoríaSM = models.CharField(max_length=255, null=True, blank=True)
    Estado = models.CharField(max_length=255, null=True, blank=True)
    IdServicio = models.CharField(max_length=255, null=True, blank=True)
    GrupoAsignado = models.CharField(max_length=255, null=True, blank=True)
    NombreMes = models.CharField(max_length=255, null=True, blank=True)
    FechaCreación = models.CharField(max_length=255, null=True, blank=True)
    ANSDías = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoOperacion = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoCliente = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoComercial = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoETB = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoTercero = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TTAbierto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoReal = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    CumpleNoCumple = models.CharField(max_length=255, null=True, blank=True)
    FaseActual = models.CharField(max_length=255, null=True, blank=True)
    NombreProducto = models.CharField(max_length=255, null=True, blank=True)
    TipoSolicitud = models.CharField(max_length=255, null=True, blank=True)
    CausalRetiro = models.CharField(max_length=255, null=True, blank=True)
    AnchoBanda = models.CharField(max_length=255, null=True, blank=True)
    MedioUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    CuentaCliente = models.CharField(max_length=255, null=True, blank=True)
    NIT = models.DecimalField(max_digits=15, decimal_places=0, null=True, blank=True)
    ProveedorUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    Asignadoa = models.CharField(max_length=255, null=True, blank=True)
    Modificadopor = models.CharField(max_length=255, null=True, blank=True)
    DireccionPrincipal = models.CharField(max_length=255, null=True, blank=True)
    SucursalInstalcion = models.CharField(max_length=255, null=True, blank=True)
    CiudadInstalacion = models.CharField(max_length=255, null=True, blank=True)
    UltimaFechaAnotación = models.CharField(max_length=255, null=True, blank=True)
    UltimaAnotaciónResumen = models.CharField(max_length=255, null=True, blank=True)
    Segmento = models.CharField(max_length=255, null=True, blank=True)
    FechaInicioContrato = models.CharField(max_length=255, null=True, blank=True)
    FechaFinContrato = models.CharField(max_length=255, null=True, blank=True)
    EstadoGestionOc = models.CharField(max_length=255, null=True, blank=True)
    FechaEstimadaEntrega = models.DateField(max_length=255, null=True, blank=True)



class Cerradas(models.Model):
    IdAprovisionamiento = models.CharField(max_length=255, null=True, blank=True)
    ViabilidadOrigen = models.CharField(max_length=255, null=True, blank=True)
    AsesorComercial = models.CharField(max_length=255, null=True, blank=True)
    TipoOperacionPlan = models.CharField(max_length=255, null=True, blank=True)
    CategoríaSM = models.CharField(max_length=255, null=True, blank=True)
    Estado = models.CharField(max_length=255, null=True, blank=True)
    IdServicio = models.CharField(max_length=255, null=True, blank=True)
    GrupoAsignado = models.CharField(max_length=255, null=True, blank=True)
    NombreMes = models.CharField(max_length=255, null=True, blank=True)
    FechaCreación = models.CharField(max_length=255, null=True, blank=True)
    ANSDías = models.CharField(max_length=255, null=True, blank=True)
    TiempoOperacion = models.IntegerField(null=True, blank=True)
    TiempoCliente = models.IntegerField(null=True, blank=True)
    TiempoComercial = models.IntegerField(null=True, blank=True)
    TiempoETB = models.IntegerField(null=True, blank=True)
    TiempoTercero = models.IntegerField(null=True, blank=True)
    TTAbierto = models.IntegerField(null=True, blank=True)
    TiempoReal = models.IntegerField(null=True, blank=True)
    CumpleNoCumple = models.CharField(max_length=255, null=True, blank=True)
    FaseActual = models.CharField(max_length=255, null=True, blank=True)
    NombreProducto = models.CharField(max_length=255, null=True, blank=True)
    TipoSolicitud = models.CharField(max_length=255, null=True, blank=True)
    CausalRetiro = models.CharField(max_length=255, null=True, blank=True)
    AnchoBanda = models.CharField(max_length=255, null=True, blank=True)
    MedioUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    CuentaCliente = models.CharField(max_length=255, null=True, blank=True)
    NIT = models.IntegerField(null=True, blank=True)
    ProveedorUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    Asignadoa = models.CharField(max_length=255, null=True, blank=True)
    Modificadopor = models.CharField(max_length=255, null=True, blank=True)
    DireccionPrincipal = models.CharField(max_length=255, null=True, blank=True)
    SucursalInstalcion = models.CharField(max_length=255, null=True, blank=True)
    CiudadInstalacion = models.CharField(max_length=255, null=True, blank=True)
    UltimaFechaAnotación = models.CharField(max_length=255, null=True, blank=True)
    UltimaAnotaciónResumen = models.CharField(max_length=255, null=True, blank=True)
    Segmento = models.CharField(max_length=255, null=True, blank=True)
    FechaFinalizacion = models.CharField(max_length=255, null=True, blank=True)
    CausalFinalizacion = models.CharField(max_length=255, null=True, blank=True)
    ObservacionesFinalizacion = models.CharField(max_length=255, null=True, blank=True)
    FechaInicioContrato = models.CharField(max_length=255, null=True, blank=True)
    FechaFinContrato = models.CharField(max_length=255, null=True, blank=True)



class Facturacion(models.Model):
    IdAprovisionamiento = models.CharField(max_length=255, null=True, blank=True)
    ViabilidadOrigen = models.CharField(max_length=255, null=True, blank=True)
    AsesorComercial = models.CharField(max_length=255, null=True, blank=True)
    TipoOperacionPlan = models.CharField(max_length=255, null=True, blank=True)
    CategoríaSM = models.CharField(max_length=255, null=True, blank=True)
    Estado = models.CharField(max_length=255, null=True, blank=True)
    IdServicio = models.CharField(max_length=255, null=True, blank=True)
    GrupoAsignado = models.CharField(max_length=255, null=True, blank=True)
    NombreMes = models.CharField(max_length=255, null=True, blank=True)  # Si necesitas un tipo específico de mes, considera agregar validaciones personalizadas
    FechaCreación = models.CharField(max_length=255, null=True, blank=True)
    ANSDías = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoOperacion = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoCliente = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoComercial = models.CharField(max_length=255, null=True, blank=True)
    TiempoETB = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoTercero = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TTAbierto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    TiempoReal = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    CumpleNoCumple = models.CharField(max_length=255, null=True, blank=True)
    FaseActual = models.CharField(max_length=255, null=True, blank=True)
    NombreProducto = models.CharField(max_length=255, null=True, blank=True)
    TipoSolicitud = models.CharField(max_length=255, null=True, blank=True)
    CausalRetiro = models.CharField(max_length=255, null=True, blank=True)
    AnchoBanda = models.CharField(max_length=255, null=True, blank=True)
    MedioUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    CuentaCliente = models.CharField(max_length=255, null=True, blank=True)
    NIT = models.DecimalField(max_digits=15, decimal_places=0, null=True, blank=True)
    ProveedorUltimaMilla = models.CharField(max_length=255, null=True, blank=True)
    Asignadoa = models.CharField(max_length=255, null=True, blank=True)
    Modificadopor = models.CharField(max_length=255, null=True, blank=True)
    DireccionPrincipal = models.CharField(max_length=255, null=True, blank=True)
    SucursalInstalcion = models.CharField(max_length=255, null=True, blank=True)
    CiudadInstalación = models.CharField(max_length=255, null=True, blank=True)
    Adicional = models.CharField(max_length=255, null=True, blank=True)
    UltimaActualizacion = models.CharField(max_length=255, null=True, blank=True)
    Segmento = models.CharField(max_length=255, null=True, blank=True)
    FechaEntregaCliente = models.CharField(max_length=255, null=True, blank=True)
    FechaInicioContrato = models.CharField(max_length=255, null=True, blank=True)
    FechaFacturacion = models.CharField(max_length=255, null=True, blank=True)
    FechaFinContrato = models.CharField(max_length=255, null=True, blank=True)



class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)