# Generated by Django 5.0.4 on 2024-05-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_abiertas_abiertasretiros_backlog_cerradas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abiertas',
        ),
        migrations.DeleteModel(
            name='AbiertasRetiros',
        ),
        migrations.DeleteModel(
            name='Cerradas',
        ),
        migrations.DeleteModel(
            name='Facturacion',
        ),
    ]
