# Generated by Django 5.0.4 on 2024-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0007_alter_backlog_accion_a_tomar_alter_backlog_ans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='Id_Aprovisionamiento',
        ),
        migrations.AddField(
            model_name='backlog',
            name='IdAprovisionamiento',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='Asesor_Comercial',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
