# Generated by Django 5.0.4 on 2024-05-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0008_remove_backlog_id_aprovisionamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='Viabilidad_Origen',
            new_name='ViabilidadOrigen',
        ),
    ]
