# Generated by Django 5.0.4 on 2024-05-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0009_rename_viabilidad_origen_backlog_viabilidadorigen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='Tiempo_Cliente',
            new_name='TiempoCliente',
        ),
    ]
