# Generated by Django 5.0.4 on 2024-05-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0011_rename_asesor_comercial_backlog_asesorcomercial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='Tipo_Operacion_Plan',
            new_name='TipoOperacionPlan',
        ),
    ]
