# Generated by Django 5.0.4 on 2024-05-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0013_rename_accion_a_tomar_backlog_accionatomar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='FechaFinalizacion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
