# Generated by Django 5.0.4 on 2024-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0015_alter_backlog_fechaseguimientostandby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='FechaFacturacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
