# Generated by Django 5.0.4 on 2024-05-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0018_alter_backlog_fechafinalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='UltimoDíaMes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
