# Generated by Django 5.0.4 on 2024-05-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0019_alter_backlog_ultimodíames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='FechaCreacion',
            new_name='FechaCreación',
        ),
    ]
