# Generated by Django 5.0.4 on 2024-05-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0020_rename_fechacreacion_backlog_fechacreación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='DELTAEQUIPOS_LB',
            new_name='DELTAEQUIPOSLB',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='FechaFacturacion',
            new_name='FechaFacturación',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='FechaFinalizacion',
            new_name='FechaFinalización',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='TiempoMedio_Bolsa',
            new_name='TiempoMedioBolsa',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='ValorProrrateado_Ingreso_Abril',
            new_name='ValorProrrateadoIngresoAbril',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='ValorProrrateado_Ingreso_Marzo',
            new_name='ValorProrrateadoIngresoMarzo',
        ),
    ]
