# Generated by Django 5.0.4 on 2024-05-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0021_rename_deltaequipos_lb_backlog_deltaequiposlb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprovisionamiento',
            old_name='cedula',
            new_name='Cedula',
        ),
        migrations.RenameField(
            model_name='aprovisionamiento',
            old_name='celula',
            new_name='Celula',
        ),
        migrations.RenameField(
            model_name='aprovisionamiento',
            old_name='lider',
            new_name='Lider',
        ),
        migrations.RenameField(
            model_name='aprovisionamiento',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='aprovisionamiento',
            old_name='usuario',
            new_name='Usuario',
        ),
    ]
