# Generated by Django 5.0.4 on 2024-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0022_rename_cedula_aprovisionamiento_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Cedula',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Celula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Lider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
