# Generated by Django 5.0.4 on 2024-05-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0024_rename_ancho_banda_abiertasretiros_anchobanda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiertasretiros',
            old_name='Id_Servicio',
            new_name='IdServicio',
        ),
    ]
