# Generated by Django 5.0.4 on 2024-05-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0026_alter_abiertasretiros_ans_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiertasretiros',
            old_name='TiempoOperacionv',
            new_name='TiempoOperacion',
        ),
    ]
