# Generated by Django 5.0.4 on 2024-05-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0027_rename_tiempooperacionv_abiertasretiros_tiempooperacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiertasretiros',
            old_name='UltimaFechaAnotacion',
            new_name='UltimaFechaAnotación',
        ),
    ]
