# Generated by Django 5.0.4 on 2024-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0028_rename_ultimafechaanotacion_abiertasretiros_ultimafechaanotación'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abiertas',
            name='ANS_Días',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Ancho_Banda',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Asesor_Comercial',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Asignado_a',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Categoría_SM',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Causal_Retiro',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Ciudad_Instalacion',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Cuenta_Cliente',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Cumple_O_No_Cumple',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Direccion_Principal',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Estado_Gestion_Oc',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Fase_Actual',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Fecha_Creación',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Fecha_Estimada_Entrega',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Fecha_Fin_Contrato',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Fecha_Inicio_Contrato',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Grupo_Asignado',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Id_Aprovisionamiento',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Id_Servicio',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Medio_Ultima_Milla',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Modificado_por',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Nombre_Mes',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Nombre_Producto',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Proveedor_Ultima_Milla',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Sucursal_Instalcion',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tiempo_Cliente',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tiempo_Comercial',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tiempo_ETB',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tiempo_Operacion',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tiempo_Real',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tiempo_Tercero',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tipo_Operacion_Plan',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Tipo_Solicitud',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Ultima_Anotación_Resumen',
        ),
        migrations.RemoveField(
            model_name='abiertas',
            name='Ultima_Fecha_Anotación',
        ),
        migrations.AddField(
            model_name='abiertas',
            name='ANSDías',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='AnchoBanda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='AsesorComercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='Asignadoa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='CategoríaSM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='CausalRetiro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='CiudadInstalacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='CuentaCliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='CumpleNoCumple',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='DireccionPrincipal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='EstadoGestionOc',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='FaseActual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='FechaCreación',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='FechaEstimadaEntrega',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='FechaFinContrato',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='FechaInicio_Contrato',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='GrupoAsignado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='IdAprovisionamiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='IdServicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='MedioUltima_Milla',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='Modificadopor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='NombreMes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='NombreProducto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='ProveedorUltimaMilla',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='SucursalInstalcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TiempoCliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TiempoComercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TiempoETB',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TiempoOperacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TiempoReal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TiempoTercero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TipoOperacionPlan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='TipoSolicitud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='UltimaAnotaciónResumen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abiertas',
            name='UltimaFechaAnotación',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='Estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='NIT',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='Segmento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='TTAbierto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='Viabilidad_Origen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
