# Generated by Django 5.0.4 on 2024-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0029_remove_abiertas_ans_días_remove_abiertas_ancho_banda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiertas',
            old_name='Viabilidad_Origen',
            new_name='ViabilidadOrigen',
        ),
    ]
