# Generated by Django 5.0.4 on 2024-05-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0030_rename_viabilidad_origen_abiertas_viabilidadorigen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiertas',
            old_name='FechaInicio_Contrato',
            new_name='FechaInicioContrato',
        ),
    ]
