# Generated by Django 5.0.4 on 2024-05-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0032_remove_cerradas_ans_días_remove_cerradas_ancho_banda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerradas',
            old_name='FechaCreacion',
            new_name='FechaCreación',
        ),
    ]
