# Generated by Django 5.0.4 on 2024-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0033_rename_fechacreacion_cerradas_fechacreación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Cedula',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
