# Generated by Django 5.0.4 on 2024-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0034_alter_aprovisionamiento_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerradas',
            name='NIT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TTAbierto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TiempoCliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TiempoComercial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TiempoETB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TiempoOperacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TiempoReal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='TiempoTercero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
