# Generated by Django 5.0.4 on 2024-05-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0037_alter_facturacion_fechaentregacliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='FechaInicioContrato',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
