# Generated by Django 5.0.4 on 2024-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0038_alter_facturacion_fechainiciocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='FechaEntregaCliente',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
