# Generated by Django 5.0.4 on 2024-05-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0039_alter_facturacion_fechaentregacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='FechaEntregaCliente',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
