# Generated by Django 5.0.4 on 2024-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0043_alter_facturacion_fechaentregacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='FechaPactadaCliente',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
