# Generated by Django 5.0.4 on 2024-06-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0046_alter_aprovisionamiento_celula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Celula',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
