# Generated by Django 5.0.4 on 2024-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0047_alter_aprovisionamiento_celula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovisionamiento',
            name='Celula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
