# Generated by Django 5.0.4 on 2024-06-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0050_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='CumploONoCumple',
            new_name='CumpleNoCumple',
        ),
    ]
