# Generated by Django 5.0.4 on 2024-06-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0051_rename_cumploonocumple_backlog_cumplenocumple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='MedioUltima_Milla',
            new_name='MedioUltimaMilla',
        ),
    ]
