# Generated by Django 5.0.4 on 2024-06-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0053_rename_proveedorultima_milla_backlog_proveedorultimamilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='ProyeccionMeLB',
            new_name='ProyeccionMesLB',
        ),
    ]
