# Generated by Django 5.0.4 on 2024-06-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0054_rename_proyeccionmelb_backlog_proyeccionmeslb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='FechaActulizacion',
            new_name='FechaActulización',
        ),
    ]
