# Generated by Django 5.0.4 on 2024-06-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0055_rename_fechaactulizacion_backlog_fechaactulización'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='UltimaAnotacion',
            new_name='UltimaAnotación',
        ),
    ]
