# Generated by Django 5.0.4 on 2024-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0059_alter_backlog_fechaentregacliente2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='PrimerDíaMes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
