# Generated by Django 5.0.4 on 2024-06-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0063_rename_semanaproyeccion_backlog_semanaproyección'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiertas',
            old_name='MedioUltima_Milla',
            new_name='MedioUltimaMilla',
        ),
        migrations.RenameField(
            model_name='cerradas',
            old_name='UltimaAnotación_Resumen',
            new_name='UltimaAnotaciónResumen',
        ),
    ]
