# Generated by Django 5.0.4 on 2024-06-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0064_rename_medioultima_milla_abiertas_medioultimamilla_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='ANSdias',
            new_name='ANSDías',
        ),
        migrations.RenameField(
            model_name='facturacion',
            old_name='CiudadInstalacion',
            new_name='CiudadInstalación',
        ),
        migrations.RenameField(
            model_name='facturacion',
            old_name='FechaCreacion',
            new_name='FechaCreación',
        ),
    ]
