# Generated by Django 5.0.4 on 2024-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0065_rename_ansdias_facturacion_ansdías_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiertasretiros',
            name='FechaCreación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
