# Generated by Django 5.0.4 on 2024-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0067_alter_abiertasretiros_fechaesperada06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiertasretiros',
            name='UltimaFechaAnotación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
