# Generated by Django 5.0.4 on 2024-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0068_alter_abiertasretiros_ultimafechaanotación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiertasretiros',
            name='FechaInicioFacturacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
