# Generated by Django 5.0.4 on 2024-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0069_alter_abiertasretiros_fechainiciofacturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiertas',
            name='FechaCreación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='FechaFinContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='FechaInicioContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
