# Generated by Django 5.0.4 on 2024-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0070_alter_abiertas_fechacreación_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiertas',
            name='EstadoGestionOc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abiertas',
            name='UltimaFechaAnotación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
