# Generated by Django 5.0.4 on 2024-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0071_alter_abiertas_estadogestionoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerradas',
            name='CausalFinalizacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='FechaCreación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='FechaFinContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='FechaInicioContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cerradas',
            name='UltimaFechaAnotación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
