# Generated by Django 5.0.4 on 2024-06-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0072_alter_cerradas_causalfinalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='FechaCreación',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='FechaEntregaCliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='FechaFacturacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='FechaFinContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='FechaInicioContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
